
[workspace]
resolver = "2" # wgpu/Bevy needs this
members = [
    "game",
    "xtask",
    "shader_builder",
    "shaders/*"
]
default-members = ["game"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
