[toolchain]
channel = "nightly-2023-04-15"
components = ["rust-src", "rustc-dev", "llvm-tools-preview"]
# commit_hash = 84dd17b56a931a631a23dfd5ef2018fd3ef49108
# rust_gpu requires specific version of toolchain
